version: "3"

services:
  dynamodb:
    build: dynamodb-container
  express:
    build: server
    command: nodemon -L
    volumes:
      - ./server:/code
  react:
    build: client
    volumes:
      - ./client:/code
    ports:
      - "3000:3000"
    command: npm start
